#ifndef OPTICAL_CMD_H_INCLUDED
#define OPTICAL_CMD_H_INCLUDED


#define OPTICAL_MAGIC 'o'
#define OPTICAL_GET_ALL		_IOR(OPTICAL_MAGIC,1,int)
#define OPTICAL_GET_SG		_IOR(OPTICAL_MAGIC,2,int)
#define OPTICAL_SET_SG_MASK	_IOW(OPTICAL_MAGIC,3,int)
#define OPTICAL_WAIT_READ	_IOR(OPTICAL_MAGIC,4,int)


#endif
